export const TOGGLE_TEST = 'TOGGLE_TEST';

export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

export const FETCH_ARTICLES_BY_TOPIC_REQUEST = ' FETCH_ARTICLES_BY_TOPIC_REQUEST';
export const FETCH_ARTICLES_BY_TOPIC_SUCCESS = ' FETCH_ARTICLES_BY_TOPIC_SUCCESS';
export const FETCH_ARTICLES_BY_TOPIC_FAILURE = ' FETCH_ARTICLES_BY_TOPIC_FAILURE';


