export const TOGGLE_TEST = 'TOGGLE_TEST';

export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';

export const GET_ARTICLES_BY_TOPIC_REQUEST = ' GET_ARTICLES_BY_TOPIC_REQUEST';
export const GET_ARTICLES_BY_TOPIC_SUCCESS = ' GET_ARTICLES_BY_TOPIC_SUCCESS';
export const GET_ARTICLES_BY_TOPIC_FAILURE = ' GET_ARTICLES_BY_TOPIC_FAILURE';

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';

export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAILURE = 'POST_COMMENT_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const PUT_ARTICLE_REQUEST = 'PUT_ARTICLE_REQUEST';
export const PUT_ARTICLE_SUCCESS = 'PUT_ARTICLE_SUCCESS';
export const PUT_ARTICLE_FAILURE = 'PUT_ARTICLE_FAILURE';

export const PUT_COMMENT_REQUEST = 'PUT_COMMENT_REQUEST';
export const PUT_COMMENT_SUCCESS = 'PUT_COMMENT_SUCCESS';
export const PUT_COMMENT_FAILURE = 'PUT_COMMENT_FAILURE';

export const GET_ARTICLE_REQEUST = 'GET_ARTICLE_REQUEST';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE';

